
services:
  database:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank_db
    volumes:
      - ./data:/var/lib/postgresql/data

  script:
    build: ./scripts/.
    restart: no
    environment:
      USER: admin
      PASSWORD: admin
      DB: bank_db
      HOST: database
      PORT: 5432
    depends_on:
      - database